### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by ffxffxwu** [Invulu/organic-profile-block#2]
After I active your plugin, I got this error:
   Uncaught TypeError: Cannot read property 'children' of undefined
    at block.js?ver=1521765980:3
    at block.js?ver=1521765980:346
The error line is `var children = blocks.source.children;`

Currently, I use cloud9 to active your plugin, not sure is it work on my local, thanks

**Comment by timbunch** [comment]
@ffxffxwu I found a workaround, pull request on it's way.
`var children = blocks.source ? blocks.source.children : null;`

**Comment by itsdavidmorgan** [comment]
I've pushed some updates to the plugin that should resolve this issue. Thanks!
